// ============================================================
// DESCRIPCIONES DE PRODUCTOS — POWERX
// Edita solo el campo 'descripcion' de cada producto.
// Deja en blanco ('') los que no tengan descripción todavía.
// ============================================================

const descripciones = [
  { nombre: "43 BCAA + GLUTAMINA", descripcion: "Fórmula que combina BCAA y Glutamina para reconstrucción muscular completa. Favorece síntesis de proteína, previene catabolismo muscular y preserva el glucógeno. Mejora rendimiento aeróbico y anaeróbico. Reduce dolor muscular post-entrenamiento. 75 servicios." },
  { nombre: "43 GAINER", descripcion: "Fórmula hipercalórica con proteína, carbohidratos y micronutrientes para incrementar peso y volumen muscular de forma efectiva." },
  { nombre: "43 RODILLERAS", descripcion: "De alta calidad para soporte y protección de rodillas durante el entrenamiento con pesas y ejercicios de alta intensidad." },
  { nombre: "43 WHEY COSTAL", descripcion: "22g de proteína de suero por servicio. 2 kg / 84 servicios. Ideal para desarrollo muscular a precio accesible." },
  { nombre: "43 ZERO 10 KG", descripcion: "Zero Carb. 30 g de proteína por servicio, cero carbohidratos. Máxima eficiencia proteica. 10 kg / 312 servicios." },
  { nombre: "43 ZERO 2.4 KG", descripcion: "Zero Carb. 30 g de proteína por servicio, cero carbohidratos, sin azúcares añadidos. 2.4 kg / 76 servicios." },
  { nombre: "43 ZERO 5 KG MULTISABOR", descripcion: "Proteína 43 Zero multisabor. Bolsitas de 1 kg en sabores: chocolate, fresa, vainilla y más. 30 g proteína, 0 carbohidratos. 150 servicios." },
  { nombre: "43 ZERO 6 KG", descripcion: "Zero Carb. 30 g de proteína por servicio, cero carbohidratos. 6 kg / 187 servicios. Económica y de alta calidad." },
  { nombre: "ACXION", descripcion: "Mejora tu cuerpo. Controla tu ingesta calórica. Controla tu apetito." },
  { nombre: "AMINO ENERGY ON CHICO", descripcion: "5 g de Aminoácidos Esenciales (EAA) con BCAA Leucina, Isoleucina y Valina. Cafeína ajustable. Para desarrollo y recuperación muscular. 30 servicios." },
  { nombre: "AMINO ENERGY ON GRANDE", descripcion: "5 g de EAA con BCAA. Cafeína ajustable para personalizar tu energía en cualquier entrenamiento. 65 servicios." },
  { nombre: "AMINO X CHICO", descripcion: "libre de estimulantes con 10 g de BCAA + L-Alanina, Taurina y L-Citrulina. Apoya resistencia durante el entreno y recuperación muscular post-ejercicio. 30 servicios." },
  { nombre: "AMINO X GRANDE", descripcion: "libre de estimulantes con 10 g de BCAA + L-Alanina, Taurina y L-Citrulina. Soporte nutricional versátil para cualquier régimen. 70 servicios." },
  { nombre: "AMINOJECT", descripcion: "6 g de BCAA fermentados por servicio. Estimula síntesis proteica y detiene procesos catabólicos. Contiene Glutamina y Betaína para recuperación ultrarrápida. 30 servicios." },
  { nombre: "ANGUS MASS", descripcion: "Ganador de masa con proteína y carbohidratos para incremento de volumen y fuerza muscular. Ideal para personas con metabolismo acelerado." },
  { nombre: "ANIMAL FLEX", descripcion: "6 g de BCAA fermentados por servicio. Estimula síntesis proteica y detiene procesos catabólicos. Contiene Glutamina y Betaína para recuperación ultrarrápida. 30 servicios." },
  { nombre: "ANIMAL PACK", descripcion: "Multivitamínico completo en paquete. Vitaminas, minerales, antioxidantes y ácidos grasos esenciales. El suplemento más completo para el" },
  { nombre: "B NOVA BCAA", descripcion: " 2:1:1 para construcción y mantenimiento muscular. Previene catabolismo durante entrenamientos intensos. Energía rápida durante el entreno. Reduce dolor muscular y acelera reparación de fibras. 50 servicios" },
  { nombre: "B NOVA CREATINA CHICA", descripcion: "El compuesto más estudiado del fitness. Mejora rendimiento en actividades de alta intensidad y corta duración. 100 servicios." },
  { nombre: "B NOVA CREATINA GRANDE", descripcion: "de alta pureza y biodisponibilidad. Mejora rendimiento en actividades de alta intensidad y corta duración. 200 servicios." },
  { nombre: "B NOVA ISO FEMME 1 KG", descripcion: "Proteína hidrolizada B Nova para mujer. Formulada con Colágeno Hidrolizado para piel, cabello y uñas, Ácido Fólico y L-Carnitina para metabolismo de grasas. 33 servicios." },
  { nombre: "B NOVA PEPTONAS", descripcion: "péptidos proteicos de alta asimilación para recuperación acelerada y síntesis proteica optimizada." },
  { nombre: "B NOVA ZERO 1 KG", descripcion: "Proteína Zero Hidrolizada B Nova — 28 g proteína, 5 g BCAA, 0 g carbohidratos. Rápida absorción y sin azúcares. Perfecta para etapas de definición o control de peso. 33 servicios." },
  { nombre: "B NOVA ZERO 4.5 KG", descripcion: "Proteína Zero Hidrolizada B Nova — 28 g proteína, 5 g BCAA, 0 g carbohidratos. Para equilibrio, energía, rendimiento y bienestar. 150 servicios." },
  { nombre: "BCAA MUTANT", descripcion: "8:1:1 con electrolitos y L-Alanil-L-Glutamina patentada. Proporción exclusiva de Leucina, Isoleucina y Valina ultra-micronizado, sin cafeína. Aumenta crecimiento muscular, promueve recuperación y previene degradación muscular." },
  { nombre: "BCAA SUPREME", descripcion: "USP Labs BCAA Supreme — 15 g de aminoácidos por porción con electrolitos y L-Alanil-L-Glutamina. Suplemento definitivo para resistencia y rendimiento incomparables. 30 servicios." },
  { nombre: "BETA ALANINA GAT", descripcion: "Aumenta niveles de carnosina muscular para mejor rendimiento en alta intensidad. Promueve resistencia muscular. Se puede usar junto a cualquier pre-entreno. 100 servicios." },
  { nombre: "BHP WHEY ULTRA", descripcion: "BHP Whey Ultra — proteína de suero natural de alta calidad nutricional. Baja en grasa y carbohidratos, rica en aminoácidos esenciales altamente asimilables. Acelera crecimiento muscular y frena catabolismo post-entrenamiento. 60 servicios." },
  { nombre: "BLACK SPIDER", descripcion: "quemador de grasa termogénico. Acelera metabolismo y aumenta energía para maximizar la pérdida de grasa durante el entrenamiento." },
  { nombre: "BLIFE 3 MAG BLEND", descripcion: "complejo de tres formas de magnesio para máxima biodisponibilidad. Apoya función muscular, nerviosa y calidad del sueño." },
  { nombre: "BLIFE 80 BILLION PROBIOTIC", descripcion: "80 mil millones de UFC de probióticos para salud digestiva, sistema inmunológico y absorción óptima de nutrientes." },
  { nombre: "BLIFE ACIDO ALFA LIPOICO", descripcion: "antioxidante universal. Apoya metabolismo energético, sensibilidad a la insulina y salud celular." },
  { nombre: "BLIFE ASHWAGANDA", descripcion: "adaptógeno para reducir cortisol y estrés. Apoya niveles de testosterona, fuerza muscular, resistencia y calidad del sueño." },
  { nombre: "BLIFE B YEAST BLEND", descripcion: "levadura de cerveza rica en vitaminas del complejo B, proteínas, minerales y betaglucanos para energía y sistema inmune." },
  { nombre: "BLIFE BOTELLA CON FUNDA", descripcion: "botella deportiva con funda aislante para mantener tus bebidas a la temperatura ideal" },
  { nombre: "BLIFE BOTELLA CON TOALLA", descripcion: "combo práctico: botella deportiva más toalla de microfibra de alta absorción." },
  { nombre: "BLIFE BOTELLA TÉRMICA", descripcion: "acero inoxidable. Bebidas frías hasta 24h y calientes hasta 12h. Ideal para pre-entrenos." },
  { nombre: "BLIFE CALCIO+D3", descripcion: "calcio con vitamina D3 para máxima absorción. Apoya salud ósea, función muscular y sistema inmunológico." },
  { nombre: "BLIFE CALOSTRO BOVINO", descripcion: "rico en inmunoglobulinas y factores de crecimiento. Apoya sistema inmune, recuperación muscular y salud intestinal." },
  { nombre: "BLIFE CITRATO DE MAGNESIO CHICO", descripcion: "forma de alta biodisponibilidad. Apoya función muscular, nerviosa, síntesis proteica y calidad del sueño. Presentación chica." },
  { nombre: "BLIFE CITRATO DE MAGNESIO GRANDE", descripcion: "forma de alta biodisponibilidad. Apoya función muscular, nerviosa, síntesis proteica y calidad del sueño. Presentación grande." },
  { nombre: "BLIFE CITRATO DE POTASIO", descripcion: "mineral esencial para función cardíaca, muscular y nerviosa. Apoya hidratación y balance electrolítico." },
  { nombre: "BLIFE COLAGENO BIO", descripcion: "colágeno hidrolizado de alta pureza. Apoya salud articular, piel, cabello y uñas con péptidos de rápida absorción." },
  { nombre: "BLIFE COLAGENO BLEND", descripcion: "combinación de tipos de colágeno para articulaciones, piel, cabello y uñas. Alta absorción y pureza." },
  { nombre: "BLIFE CREATINA", descripcion: "creatina monohidratada con soporte de fuerza muscular, potencia, recuperación y propiedades antioxidantes." },
  { nombre: "BLIFE D3 PLUS", descripcion: "vitamina D3 de alta potencia para sistema inmunológico, salud ósea, función muscular y estado de ánimo." },
  { nombre: "BLIFE ELECTRO BLEND + CREATINA", descripcion: "combina creatina con electrolitos esenciales. Hidratación óptima y rendimiento muscular mejorado." },
  { nombre: "BLIFE GLICINATO DE MAGNESIO", descripcion: "forma quelada de alta biodisponibilidad sin efectos digestivos. Ideal para relajación muscular y sueño." },
  { nombre: "BLIFE JOINT BLEND", descripcion: "fórmula completa para articulaciones con glucosamina, condroitina, colágeno y MSM." },
  { nombre: "BLIFE KIT TOALLAS", descripcion: "set de toallas deportivas de microfibra con alta absorción, secado rápido y antibacterial." },
  { nombre: "BLIFE MACA BLEND", descripcion: "extracto de maca peruana para energía, resistencia, libido y equilibrio hormonal." },
  { nombre: "BLIFE MENS BLEND", descripcion: "multivitamínico para hombres con vitaminas, minerales y extractos botánicos para energía y salud masculina." },
  { nombre: "BLIFE MENS T PLATINUM", descripcion: "precursor de testosterona premium. Apoya niveles hormonales, masa muscular, fuerza y vitalidad masculina." },
  { nombre: "BLIFE MYO INOSITOL", descripcion: "apoya sensibilidad a la insulina, función ovárica, equilibrio hormonal y salud metabólica." },
  { nombre: "BLIFE OMEGA 3 CHICO", descripcion: "EPA y DHA para salud cardiovascular, cerebral, articular y reducción de inflamación. Presentación chica." },
  { nombre: "BLIFE OMEGA 3 GRANDE", descripcion: "EPA y DHA de alta concentración para salud cardiovascular, cerebral y articular. Presentación grande." },
  { nombre: "BLIFE RESVERATROL", descripcion: "potente antioxidante de uva para salud cardiovascular, antiinflamatorio y longevidad celular." },
  { nombre: "BLIFE TRIBULUS", descripcion: "extracto de Tribulus Terrestris para apoyo hormonal, libido, energía y rendimiento deportivo." },
  { nombre: "BLIFE VITAMINA E+BIOTINA", descripcion: "antioxidante potente más biotina para salud de piel, cabello, uñas y sistema nervioso." },
  { nombre: "BLIFE WOMENS BLEND", descripcion: "multivitamínico especializado para mujeres con vitaminas, minerales, hierro y extractos para salud femenina integral." },
  { nombre: "C4 ORIGINAL CHICO", descripcion: "el pre-entreno #1 en América. Energía avanzada, resistencia, concentración y bombeo muscular. Fórmula clásica clinicamente estudiada. 30" },
  { nombre: "C4 ORIGINAL GRANDE", descripcion: " el pre-entreno #1 en América. Energía avanzada, resistencia, concentración y bombeo muscular. Desde principiantes hasta competidores de élite. 50 servicios." },
  { nombre: "CAFEINA GAT", descripcion: "200 mg de cafeína pura por tableta. Sin azúcar ni calorías. Mejora enfoque, alerta, tiempo de reacción y resistencia. 100 tabletas." },
  { nombre: "CAFEINA MUTANT", descripcion: "200 mg de cafeína anhidra de grado farmacéutico. 240 tabletas producidas bajo inspección gubernamental para máxima pureza. Energiza el entreno y mejora concentración mental." },
  { nombre: "CARBOTEIN", descripcion: "" },
  { nombre: "CARNIVOR", descripcion: "primer aislado de proteína de carne más concentrado que el suero. A través de extracción, clarificación e hidrólisis entrega proteína pura a tejidos musculares. Más aminoácidos que cualquier otra fuente proteica. 56 servicios." },
  { nombre: "CARNIVOR MASS", descripcion: " ganador de masa con proteína de carne hidrolizada. Sin lactosa ni soya. Para construcción de masa muscular limpia y ganancia de fuerza." },
  { nombre: "CBUM ESSENTIAL CHICO", descripcion: "formulado por 5× Mr. Olympia Chris Bumstead. 4 g L-Citrulina para bombeo, 3.2 g Beta Alanina para combatir fatiga, 200 mg cafeína para energía óptima. 30 servicios." },
  { nombre: "CBUM ITHOLATE CHICA", descripcion: "formulada por 5× Mr. Olympia Chris Bumstead. Aislado de suero 100% microfiltrado. 25 g de proteína de la más alta calidad, máxima digestibilidad. 25 servicios." },
  { nombre: "CBUM ITHOLATE GRANDE", descripcion: "formulada por 5× Mr. Olympia Chris Bumstead. 25 g aislado de suero 100% microfiltrado, máxima digestibilidad. 73 servicios." },
  { nombre: "CELL TECH 3LBS", descripcion: "creatina para fuerza y volumen muscular. 79% hidratos de carbono de lenta y rápida absorción + creatina + aminoácidos esenciales. Testado en 30+ estudios. Ideal post-entreno. 27 servicios." },
  { nombre: "CELL TECH 6LBS", descripcion: "fórmula de creatina científicamente desarrollada para personas que buscan ganar tamaño y fuerza. 54 servicios." },
  { nombre: "CELL TECH CREACTOR", descripcion: "clorhidrato de creatina (HCL) con creatina de ácido libre. Con-Cret® para mejor absorción, menor retención de líquidos. Formas ultra puras y más concentradas que monohidrato. 120 servicios." },
  { nombre: "CINTURON", descripcion: "soporte lumbar para pesas. Protege la espalda baja durante sentadilla, peso muerto y ejercicios de alta carga. Personalizable" },
  { nombre: "CITRULINA ADVANCED", descripcion: "60 servicios de L-Citrulina pura. Precursor de arginina y óxido nítrico. Mejora masa muscular, fuerza, acelera recuperación y reduce dolor muscular post-ejercicio." },
  { nombre: "CITRULINA INSANE", descripcion: "60 servicios de L-Citrulina pura. Amplifica el bombeo muscular, mejora la resistencia y acelera la recuperación intra-entreno." },
  { nombre: "CLA 1250 GAT", descripcion: "ácido linoleico conjugado para mantenimiento de masa muscular y reducción de grasa corporal. Suplemento natural derivado del aceite de cártamo." },
  { nombre: "CLA+CARNITINA BPI", descripcion: "CLA preserva músculo y Carnitina transporta ácidos grasos a la mitocondria como energía. Sinergia para quema de grasa eficaz." },
  { nombre: "COFFEE MAX", descripcion: "el primer café pre-entreno del mundo. Combina beneficios del café con potente fórmula de pre-entreno de alta calidad. Impulso explosivo de energía, resistencia y enfoque. 30 servicios." },
  { nombre: "COLÁGENO HIDROLIZADO SHE FIT", descripcion: "colágeno específico para mujer. Apoya salud de articulaciones, piel, cabello y uñas con alta biodisponibilidad." },
  { nombre: "COLÁGENO META", descripcion: " colágeno hidrolizado para soporte articular, salud de piel, cabello y uñas con péptidos de rápida absorción." },
  { nombre: "CREATINA BIRDMAN", descripcion: "micronizada y de alta pureza. Libre de saborizantes y endulzantes. Puede agregarse a cualquier bebida. Ideal para atletas veganos. 90 servicios." },
  { nombre: "CREATINA CELLUCOR", descripcion: "Creatine 360 g. Ideal para levantamiento de pesas y deportes de alto impacto. Apoya producción de ATP y recuperación muscular más rápida. 72" },
  { nombre: "CREATINA CREAKON CX8", descripcion: "combina 8 formas de creatina (monohidrato, malato, quelato de magnesio y más) para absorción y biodisponibilidad óptimas. 30 servicios." },
  { nombre: "CREATINA DRAGON CHICA", descripcion: "Creatina Monohidratada Essentials — soporte de fuerza muscular, potencia, recuperación y antioxidante. 60 servicios." },
  { nombre: "CREATINA DRAGON GRANDE", descripcion: "Creatina Monohidratada Essentials — soporte de fuerza muscular, potencia, recuperación y antioxidante. Presentación económica. 200 servicios." },
  { nombre: "CREATINA ELECTROLYTE", descripcion: "5 g creatina monohidratada pura + electrolitos esenciales + glicinato de magnesio + vitaminas C, D, E, B12. La forma más refrescante de tomar creatina. 30 servicios." },
  { nombre: "CREATINA GAT CHICA", descripcion: "monohidrato de calidad farmacéutica. Resintetiza ATP, mejora fuerza muscular, torsión y rendimiento. 60 servicios." },
  { nombre: "CREATINA GAT GRANDE", descripcion: "monohidrato de calidad farmacéutica. Clínicamente demostrado para mejorar fuerza, torsión y rendimiento deportivo. 200 servicios." },
  { nombre: "CREATINA HI TECH CHICA", descripcion: " monohidrato con 99.5% de pureza verificada por HPLC. Fuente de energía química para contracción muscular. 80 servicios." },
  { nombre: "CREATINA HI TECH GRANDE", descripcion: " monohidrato con 99.5% de pureza verificada por HPLC. Más ATP = más energía para deportes de velocidad y culturismo. 200 servicios." },
  { nombre: "CREATINA INSANE", descripcion: "monohidrato de creatina más puro del mercado. Se mezcla fácilmente, puede combinarse con pre-entreno Insane Labz. Mejora fuerza muscular. 60 servicios." },
  { nombre: "CREATINA META", descripcion: "monohidrato para aumentar fuerza. Incrementa potencia, tamaño y fuerza muscular en alta intensidad. Transporta ATP a miofibrillas. 100 servicios." },
  { nombre: "CREATINA NUTREX CHICA", descripcion: "proceso patentado de máxima concentración. Dosis concentradas que se reflejan rápidamente en plasma sanguíneo. 200 servicios." },
  { nombre: "CREATINA NUTREX GRANDE", descripcion: "5000 mg por porción con micronización para absorción óptima. Un frasco de 600 g ofrece suministro de hasta 4 meses. 120 servicios." },
  { nombre: "CREATINA ON", descripcion: "creatina monohidratada sin sabor. 60 servicios. Suplemento de alta calidad que aporta tamaño, fuerza y rendimiento muscular." },
  { nombre: "CREATINA PLATINUM", descripcion: "5000 mg de creatina monohidratada de alta pureza por dosis. Ayuda a la hidratación celular y potencializa el crecimiento muscular. 80 servicios." },
  { nombre: "CREATINA RC CHICA", descripcion: "Creapure® la forma de creatina más estudiada. Sin sabor, para mezclar con cualquier bebida. Apoya ATP para entrenamientos explosivos. 120 servicios." },
  { nombre: "CREATINA RC GRANDE", descripcion: "Creapure® certificada. Mejora desempeño atlético, aumenta fuerza y resistencia, favorece ganancia de masa muscular. 400 servicios." },
  { nombre: "CREATINA ULTRA BHP 300 GRS", descripcion: "la primera creatina molecularmente modificada. 10× más pequeña que monohidrato. Aumenta creatina intramuscular y favorece fuerza sin retención de líquidos. 60 servicios." },
  { nombre: "CREATINA ULTRA BHP 500 GRS", descripcion: "primera creatina molecularmente modificada de alta concentración. Sin retención de líquidos, mayor fuerza y rendimiento. 100 servicios." },
  { nombre: "DEFIT CREATINA CHICA", descripcion: "energía pura en cada porción. Incrementa fuerza muscular, mejora resistencia y acelera recuperación tras entrenamientos intensos. 100 servicios." },
  { nombre: "DEFIT CREATINA GRANDE", descripcion: " fórmula de alta pureza para construir masa muscular magra y transformar el esfuerzo en resultados visibles. 200 servicios." },
  { nombre: "DEFIT FIT FEMME", descripcion: "Isolate Whey más Colágeno. Diseñada para mujeres. Fortalece el cuerpo, acelera la recuperación y mejora la elasticidad de la piel. 33 servicios." },
  { nombre: "DEFIT ISOLATE WHEY CHICA", descripcion: "proteína aislada 100% sin carbohidratos. 26 g de proteína por servicio, sin grasas trans ni azúcares añadidos. De fácil digestión. 33 servicios." },
  { nombre: "DEFIT ISOLATE WHEY GRANDE", descripcion: "proteína aislada sin carbohidratos. 26 g de proteína, alta calidad nutricional y pureza para mejores resultados. 73 servicios." },
  { nombre: "DEFIT PEPTONAS", descripcion: "péptidos proteicos de alta asimilación para recuperación acelerada y síntesis proteica optimizada." },
  { nombre: "DEMON BCAA", descripcion: " aminoácidos de cadena ramificada: favorecen síntesis proteica, previenen catabolismo, preservan glucógeno, mejoran rendimiento aeróbico y anaeróbico, reducen dolor muscular post-entreno y apoyan el sistema inmunológico. 60 servicios." },
  { nombre: "DEMON DUST", descripcion: "pre-entreno que provee energía gradual por hasta 5 horas continuas. Perfecto para rutina, cardio y salir del gimnasio lleno de energía. 50 servicios." },
  { nombre: "ELITE WHEY 5 LBS", descripcion: "absorción rápida con sabor irresistible. 23 g proteína, 5.5 g BCAA, 2.7 g leucina, 2 g azúcar. Sin gluten. Mézclalo antes del entreno o úsalo como snack proteico. 67 servicios." },
  { nombre: "EVP 3D", descripcion: "pre-entreno sin estimulantes. Para quienes son sensibles a la cafeína o entrenan de noche. Garantiza el descanso adecuado. Enfoque mental, bomba e intensidad sin cafeína. 40 servicios." },
  { nombre: "EVP XTREME", descripcion: "ignitor de bomba élite con nitrato de arginina, citrulina, extracto de cabeza de leon, yohimbe, cafeína natural y dicafeína malato. Energía, bomba e intensidad para físicos extremos. 40 servicios." },
  { nombre: "FALCON PERFORMANCE", descripcion: "proteína 100% vegetal con creatina, BCAA, enzimas proteolíticas, cúrcuma (Turmipure) y cereza (VitaCherry Sport). 31 g proteína vegetal + 3 g creatina + 6 g BCAA. Libre de lácteos, gluten y soya. 19" },
  { nombre: "FARMACOLOGIA ROTTERDAM", descripcion: "productos farmacológicos. Consulta disponibilidad, presentaciones y requisitos en tienda." },
  { nombre: "FARMACOLOGIA SYNTEX LABS", descripcion: " línea farmacológica. Consulta disponibilidad, presentaciones y requisitos de compra en tienda." },
  { nombre: "FARMACOLOGIA XT LABS", descripcion: "productos farmacológicos.Consulta disponibilidad, presentaciones y requisitos en tienda." },
  { nombre: "FITMINGO", descripcion: "proteína 100% vegetal con Ácido Hialurónico, Svetol®, Inositol, PureWay-C® (Vitamina C), Vitamina D3 de origen vegetal y ZincNova. 24 g proteína vegetal. OptiZiome P3 Hydrolyzer para mejor digestión. Libre de lácteos, gluten y soya. 30 servicios." },
  { nombre: "FLEXX EAAS", descripcion: "los 9 aminoácidos esenciales (EAA) para síntesis completa de proteínas musculares. 7 g EAAs + 125 mg Ashwagandha Sensoril® para mitigar estrés. Soporte de hidratación pre, intra y post-entreno. 30 servicios." },
  { nombre: "GAINER ULTRA", descripcion: "ganador de masa hipercalórico con proteína, carbohidratos complejos y vitaminas. Ideal para ectomorfos y personas con dificultad para ganar peso." },
  { nombre: "GHOST LEGEND PWO", descripcion: " pre-entreno con L-Citrulina premium. 100% vegano. Bomba sin molestia estomacal. Fórmula de energía y enfoque con sabores icónicos en colaboraciones auténticas. 30 servicios." },
  { nombre: "GHOST WHEY 2 LBS", descripcion: "mezcla premium de proteína de suero al 100% con enzimas digestivas y sorprendentes colaboraciones de sabores auténticos. 27 servicios." },
  { nombre: "GLUTAMINA PURE CHICA", descripcion: " el aminoácido más abundante en la musculatura. Favorece síntesis proteica, previene catabolismo, preserva glucógeno y mejora rendimiento aeróbico y anaeróbico. Reduce dolor muscular post-entreno. Presentación chica." },
  { nombre: "GLUTAMINA PURE GRANDE", descripcion: "componente indispensable para masa muscular. Favorece síntesis proteica, previene catabolismo y mejora rendimiento. Reduce dolor muscular post-entreno. Presentación grande." },
  { nombre: "GLUTAMINA GAT", descripcion: "soporte para masa muscular y recuperación. Previene catabolismo, refuerza sistema inmunológico y mejora recuperación post-entreno." },
  { nombre: "GLUTAMINA MUTANT", descripcion: " L-Glutamina de alta pureza para recuperación muscular, apoyo inmunológico y salud intestinal." },
  { nombre: "GLUTAMINA PLATINUM", descripcion: " L-Glutamina premium para síntesis proteica, recuperación y refuerzo del sistema inmunológico." },
  { nombre: "GOLD STANDARD 10 LBS", descripcion: " la proteína más prestigiosa del mundo. 24 g proteína + 5.5 g BCAA para construir músculo y aumentar fuerza. Sin gluten. 146 servicios." },
  { nombre: "GOLD STANDARD 2 LBS", descripcion: " 24 g proteína + 5.5 g BCAA. Sin gluten. La proteína más premiada para desarrollo y recuperación muscular. 27 servicios." },
  { nombre: "GOLD STANDARD 5 LBS", descripcion: "24 g proteína + 5.5 g BCAA. Sin gluten. La fórmula de referencia en el mundo del fitness. 73 servicios." },
  { nombre: "GOLD STANDARD ISOLATE", descripcion: " proteína aislada hidrolizada y ultra-filtrada. 24 g proteína + 5.5 g BCAA. Alta calidad para construcción muscular y fuerza. 76 servicios." },
  { nombre: "HYDROTEIN", descripcion: " suero hidrolizado de alta calidad. 23 g proteína por porción, 65 porciones. Absorción rápida. Rica en EAA, BCAA y glutamina para rendimiento físico óptimo." },
  { nombre: "HYDROXYCUT HARDCORE ELITE", descripcion: "quemador termogénico avanzado. Energía aumentada, enfoque mental y termogénesis elevada para máximos resultados." },
  { nombre: "INSANE VEINZ", descripcion: "pre-entreno NO estimulante que aumenta vascularización durante el entrenamiento y horas después. Bombeo de élite sin cafeína. 35 servicios." },
  { nombre: "ISOPHORM", descripcion: "25 g de proteína pura hidrolizada. La hidrólisis enciende síntesis proteica y maximiza potencial de crecimiento y reparación muscular. 77 servicios." },
  { nombre: "ISO 100 1.3 LBS", descripcion: " ultra-purificada. 25 g proteína, 120 cal, 1 g azúcar, 5.5 g BCAA, 2.6 g leucina por servicio. 20 servicios." },
  { nombre: "ISO 100 3 LBS", descripcion: "filtrada para eliminar lactosa, carbohidratos y grasa. 25 g proteína, 1 g azúcar, 5.5 g BCAA, 2.6 g leucina. 43 servicios." },
  { nombre: "ISO 100 5 LBS", descripcion: " una de las proteínas de mayor calidad del mercado. 25 g proteína + 5.5 g BCAA + 2.6 g leucina. Potencia ultra rápida de absorción. 71 servicios." },
  { nombre: "ISOFIT", descripcion: "25 g aislado de suero + 12 g EAA + 5.9 g BCAA por porción. Combustible de precisión para crecimiento muscular, fuerza y recuperación. 70 servicios." },
  { nombre: "ISOPURE", descripcion: " 100% proteína aislada sin carbohidratos. 25 g proteína por servicio. Sin gluten, sin lactosa. Cargada de vitaminas y minerales. 44 servicios." },
  { nombre: "ISOPURE GRANDE", descripcion: " 100% proteína aislada sin carbohidratos. 25 g proteína por servicio. Sin gluten, sin lactosa. Cargada de vitaminas y minerales. 62 servicios." },
  { nombre: "JOINT SUPPORT GAT", descripcion: "colágeno y soporte articular. Fórmula completa para proteger tendones, ligamentos y cartílagos durante entrenamientos de alta intensidad." },
  { nombre: "L ARGININA GAT", descripcion: " precursor de óxido nítrico. Promueve vasodilatación, desarrollo y recuperación muscular. Estimula hormona de crecimiento, quema de grasa y mejora circulación. Forma libre para mejor absorción. 180 cápsulas." },
  { nombre: "L CARNITINA GAT CAPS", descripcion: "transporta ácidos grasos a la mitocondria como fuente de energía. Apoya pérdida de grasa, resistencia y recuperación muscular." },
  { nombre: "L CARNITINA ULTRA LIQUIDA", descripcion: "absorción inmediata en formato líquido. Metabolismo de grasas optimizado, mayor energía y resistencia durante el cardio." },
  { nombre: "LIPO 6 BLACK HERS 60 CAPS", descripcion: "quemador de grasa especializado para mujeres. Alta potencia para pérdida de grasa, supresión de apetito y aumento de energía. 60 cápsulas." },
  { nombre: "LIPO 6 BLACK ROJO 120 CAPS", descripcion: " quemador de grasa termogénico avanzado para pérdida de grasa, aumento de energía y enfoque mental. 120 cápsulas." },
  { nombre: "LIPODRENE AMARILLO", descripcion: "quemador termogénico para pérdida de peso, energía aumentada y supresión de apetito." },
  { nombre: "LIPODRENE NEGRO", descripcion: " quemador de grasa de alta potencia con fórmula mejorada. Termogénico avanzado para pérdida de grasa y energía." },
  { nombre: "LIPODRENE VERDE", descripcion: "versión verde del quemador premium. Termogénico potente con ingredientes seleccionados para resultados óptimos." },
  { nombre: "MADNESS MUTANT", descripcion: "pre-entreno ultra concentrado. Cafeína de doble fuente ultra concentrada. Fórmula legendaria para superar los límites de energía y estimular mayor crecimiento muscular. 30 servicios." },
  { nombre: "MAGNESIO BHP CAPS", descripcion: " mineral esencial para función muscular, nerviosa, síntesis proteica y calidad del sueño. Alta biodisponibilidad para atletas activos." },
  { nombre: "MASS TECH EXTREME 2000", descripcion: " ganador de masa hipercalórico. 2000 calorías por servicio con proteína de alta calidad y carbohidratos complejos para aumento rápido de masa muscular." },
  { nombre: "MESOFRANCE ANTIOBESIDAD", descripcion: " fórmula especializada para control de peso. Uso bajo supervisión médica. Consulta disponibilidad y requisitos en tienda." },
  { nombre: "MESOFRANCE LIPOENZIMAS", descripcion: "suplemento enzimático para metabolismo de lípidos. Apoya digestión y metabolismo de grasas. Consulta disponibilidad en tienda." },
  { nombre: "MESOFRANCE PEPTONAS", descripcion: "péptidos de alta asimilación para recuperación y desarrollo muscular. Fórmula especializada de absorción rápida." },
  { nombre: "MESOFRANCE REDUGRASS", descripcion: "fórmula para reducción de peso y medidas. Apoyo en control de peso corporal y grasa localizada. Consulta disponibilidad en tienda." },
  { nombre: "MULTI VITAMIN + TEST CHICO", descripcion: " multivitamínico con soporte de testosterona. Vitaminas, minerales y precursores para salud masculina y rendimiento deportivo. Presentación chica." },
  { nombre: "MULTI VITAMIN + TEST GRANDE", descripcion: "fórmula completa para hombres activos con vitaminas, minerales y precursores hormonales. Presentación grande." },
  { nombre: "MULTIVITAMINICO PLATINUM", descripcion: " multivitamínico completo para atletas. Vitaminas esenciales, minerales y antioxidantes para rendimiento óptimo y bienestar general." },
  { nombre: "MUTANT MASS CHICO", descripcion: "ganador de masa premium con proteína de múltiples fuentes, carbohidratos y MCTs para máxima ganancia de masa muscular. Presentación chica." },
  { nombre: "MUTANT MASS GRANDE", descripcion: " ganador de masa premium. Alto en calorías, proteínas y carbohidratos de calidad para incremento de peso y volumen muscular. Presentación grande." },
  { nombre: "MUTANT WHEY 10 LBS", descripcion: "proteína #1 en ventas. 22 g proteína de suero, 10.4 g EAAs, 5 g BCAAs. Sin aspartame, con enzimas digestivas para absorción óptima. Proteína real verificada. 122 servicios." },
  { nombre: "MUTANT WHEY 5 LBS", descripcion: "proteína #1 en ventas. 22 g proteína, 10.4 g EAA, 5 g BCAA. Sin aspartame, con enzimas digestivas. Mejor sabor y mezcla mejorada. 61 servicios." },
  { nombre: "MUTANT WHEY DUAL", descripcion: " 22 g proteína, 10.4 g EAA, 5 g BCAA. Sin aspartame, con enzimas digestivas para optimizar resultados. 50 servicios." },
  { nombre: "NITRAFLEX", descripcion: "fórmula de alta densidad clínicamente probada con citrulina, beta alanina y arginina. Incrementa energía, concentración, fuerza, resistencia, bombeos y mejora testosterona durante el entrenamiento. 30 servicios." },
  { nombre: "NITRO TECH PERFORMANCE 4 LBS", descripcion: " proteína limpia y simple. 30 g de proteína de péptidos de suero y aislado, las más limpias y puras del mercado. 41 servicios." },
  { nombre: "NITRO TECH WHEY GOLD 2 LBS", descripcion: " aislado y concentrado de alta calidad con péptidos. 24 g proteína + 5.5 g BCAA + 4 g glutamina. Baja en grasas y carbohidratos. 28 servicios." },
  { nombre: "NITRO TECH WHEY GOLD 5 LBS", descripcion: "24 g proteína + 5.5 g BCAA + 4 g glutamina. Rápida absorción, ideal para post-entreno. Baja en grasas y carbohidratos. 76 servicios." },
  { nombre: "NITROTECH RIPPED 4 LBS", descripcion: "promueve pérdida de grasa y mantenimiento de masa muscular. 30 g proteína + 250 mg CLA + 500 mg L-Carnitina por servicio. 42 servicios." },
  { nombre: "OMEGA 3 GAT", descripcion: "EPA y DHA de alta concentración para salud cardiovascular, función cerebral, reducción de inflamación y salud articular en atletas." },
  { nombre: "OPTI MEN", descripcion: "multivitamínico completo para hombres activos. Vitaminas, minerales, aminoácidos, enzimas y extractos botánicos para rendimiento y salud integral." },
  { nombre: "OPTI WOMEN", descripcion: " multivitamínico especializado para mujeres activas. Vitaminas, minerales, hierro y extractos botánicos formulados para necesidades femeninas." },
  { nombre: "PHANTOM XS", descripcion: "quemador de grasa avanzado. Termogénico de alta potencia para pérdida de grasa, aumento de energía y enfoque mental durante el entrenamiento." },
   { nombre: "PHARLABS ISOLATE", descripcion: "Proteína whey isolatada con 25G de proteína por scoop, 4.4G de glutamina, 5.9G de BCAAs, 12G EAAs, rinde 70 servicios" },
  { nombre: "PSYCHOTIC DORADO", descripcion: " mayor rendimiento en el entrenamiento. Resistencia ilimitada y bombeos de locura sin bajones. Beta-alanina, monohidrato de creatina y DMAE para resistencia y enfoque. 35 servicios." },
  { nombre: "PSYCHOTIC NEGRO", descripcion: "mayor concentración y energía con menos cafeína. Ideal para quienes quieren el empujón extra con estímulo moderado. 35 servicios." },
  { nombre: "PSYCHOTIC ROJO CHICO", descripcion: " pre-entreno de alta intensidad. Matriz de estimulantes extrema con cafeína anhidra, PEA, yohimbina y Rauwolfia Vomitoria. Matriz de óxido nítrico avanzada con L-Citrulina, agmatina sulfato y nitrato de betaína. Beta alanina y creatinol-o-fosfato para resistencia extrema. 35 servicios." },
  { nombre: "PSYCHOTIC ROJO GRANDE", descripcion: "energía explosiva, enfoque láser y conexión mente-músculo inigualable. Vasodilatación extrema y vascularización impresionante. La fórmula más intensa de Insane Labz. 60 servicios." },
  { nombre: "PSYCHOTIC SAW", descripcion: "el pre-entreno más loco de Mad Chemist. Ingredientes que trabajan juntos para matar en el gimnasio. Contiene OxyGold® (ácido fúlvico) para resistencia, adaptación muscular, absorción de nutrientes y producción saludable de testosterona. 30 servicios." },
  { nombre: "PSYCHOTIC SAW GRANDE", descripcion: "el pre-entreno más loco de Mad Chemist. Ingredientes que trabajan juntos para matar en el gimnasio. Contiene OxyGold® (ácido fúlvico) para resistencia, adaptación muscular, absorción de nutrientes y producción saludable de testosterona. 60 servicios." },
  { nombre: "PSYCHOTIC SOBRES NEGRO", descripcion: "30 sobres individuales. Concentración y energía con estímulo moderado en formato portátil." },
  { nombre: "PSYCHOTIC SOBRES ROJO", descripcion: "30 sobres individuales. La fórmula épica de alta intensidad en paquetes convenientes de un servicio." },
  { nombre: "PYSCHOTIC SOBRES DORADO", descripcion: "30 sobres individuales. Resistencia ilimitada y bombeos de locura en formato portátil ideal para viajes." },
  { nombre: "REYKON CREATINA GRANDE", descripcion: "creatina que aumenta potencia muscular, acelera recuperación post-entreno y retarda fatiga muscular para entrenamientos prolongados. 260 servicios." },
  { nombre: "REYKON PRIMATE BURST", descripcion: " 25 g proteína aislada + 5.5 g BCAA + 3 g leucina. Nutrición muscular superior y recuperación rápida con incremento en fuerza. 73 servicios." },
  { nombre: "REYKON ZERO 1 KG", descripcion: "proteína de suero hidrolizada, cero carbohidratos, absorción ultrarrápida. Pureza y rendimiento para atletas que llevan su cuerpo al límite. 28 servicios." },
  { nombre: "REYKON ZERO 10 KG", descripcion: "proteína de suero hidrolizada para guerreros del rendimiento. 264 servicios de absorción ultrarrápida con cero carbohidratos." },
  { nombre: "REYKON ZERO 6 KG", descripcion: " proteína de suero hidrolizada sin carbohidratos. 171 servicios de alta calidad y pureza para construcción muscular." },
  { nombre: "REYKON ZERO MULTISABOR", descripcion: "6 kg con 6 sabores: chocobanana, fresa, triple chocolate, nuez, vainilla y galleta. La alianza perfecta entre deleite sensorial y construcción muscular. 157 servicios." },
  { nombre: "RONNIE WHEY XS", descripcion: "20 g proteína de calidad por cucharada a precio asequible. 3.7 g glutamina + 4 g BCAA + 8.6 g EAA. Solo 2 g grasa y 4 g azúcar por porción. 60" },
  { nombre: "RYSE LOADED PRE", descripcion: " pre-entreno con fórmula única que aumenta resistencia y energía para entrenar con más intensidad durante más tiempo. 30 servicios." },
  { nombre: "SERIOUS MASS CHICO", descripcion: "ganador de peso con proteína de alta calidad, carbohidratos complejos, vitaminas y minerales para ganar masa muscular. Presentación chica." },
  { nombre: "SERIOUS MASS GRANDE", descripcion: " ganador de peso premium con proteína de alta calidad, carbohidratos complejos y micronutrientes para máxima ganancia de masa. Presentación grande." },
  { nombre: "SHAKER COLOR LISO", descripcion: "botella mezcladora profesional con bola mezcladora para mezclas perfectas sin grumos. Sin BPA." },
  { nombre: "SHAKER SYNTRAX", descripcion: "botella deportiva de alta calidad para mezcla de suplementos. Diseño práctico y ergonómico." },
  { nombre: "SHAKER GARRAFON", descripcion: "shaker de gran capacidad para atletas que necesitan mayor volumen de bebidas y suplementos durante el entrenamiento." },
  { nombre: "SHAKER SUPER HEROES", descripcion: "Shaker de super heroes, diferentes diseños, ideal para tu suplemento, capacidad 700ml" },
  { nombre: "STRAPS (CAYERAS)", descripcion: "esencial para mejorar el agarre en dominadas, peso muerto y remos. Protege muñecas y mejora el desempeño." },
  { nombre: "SUPER PUMP MAX", descripcion: " pre-entreno único con 4 g L-Citrulina + 4 g L-Leucina. Energía intensa, concentración, bombeos alucinantes y anabolismo muscular. Con electrolitos para mayor hidratación. 40 servicios." },
  { nombre: "SYNTHA 6", descripcion: "mezcla de concentrado + aislado + caseinato + caseína micelar + proteína de leche + albumina de huevo. 22 g proteína + 10 g aminoácidos esenciales. 48 servicios." },
  { nombre: "TESTROL GOLD", descripcion: " precursor de testosterona avanzado. Ingredientes clinicamente estudiados para hombres que buscan aumentar testosterona, masa muscular y rendimiento atlético." },
  { nombre: "TESTROL ORIGINAL", descripcion: "precursor de testosterona con fórmula herbal. Apoya niveles hormonales naturales, libido, fuerza y rendimiento físico." },
  { nombre: "THE CURSE", descripcion: " el suplemento más potente del mercado. Energía y fuerza muscular extrema. Concentración mental única. Aumenta al máximo la producción de óxido nítrico. 50 servicios." },
  { nombre: "TOTAL WAR", descripcion: " pre-entreno completo galardonado y #1 en ventas. 320 mg cafeína para energía duradera + 6 g L-Citrulina para bombeos intensos + 3.2 g Beta Alanina para resistencia muscular. 30 servicios." },
  { nombre: "VAPOR X", descripcion: "pre-entreno neurosensorial. Energía explosiva, concentración mental, bombeos musculares máximos, mejora de fuerza y resistencia. 30 servicios." },
  { nombre: "VEGAN NATURALS", descripcion: " proteína 100% vegetal. 25 g proteína vegetal por porción con alta digestibilidad. Libre de lácteos, gluten y soya. Ideal para atletas veganos. 57 servicios." },
  { nombre: "VENOM INFERNO", descripcion: " pre-entreno altamente estimulante más vendido del año. Estimula energía y fuerza, aumenta resistencia al estrés, nootrópicos para enfoque mental. 40 servicios." },
  { nombre: "VITAMINA C INSANE", descripcion: "suplemento de alta potencia para sistema inmunológico, antioxidante y recuperación de atletas." },
  { nombre: "WHEY HD", descripcion: "proteína de suero premium con tecnología de sabor avanzada. Para masa muscular magra y recuperación. Mínimo de grasa, sodio y azúcares. 50" },
  { nombre: "XTINCTION MULTISABOR", descripcion: "proteína hidrolizada 5 kg con 5 bolsas de 1 kg en diferentes sabores. 25 g proteína, 0 g grasas trans, 0 g azúcar por servicio. 167 servicios." },
  { nombre: "YOHIMBINE", descripcion: " extracto de yohimbe estandarizado. Apoya quema de grasa en áreas problemáticas. Aumenta energía y libido." },
  { nombre: "ZMAG GAT", descripcion: "complejo ZMA de zinc, magnesio y vitamina B6. Apoya recuperación muscular, niveles de testosterona, calidad del sueño y rendimiento atlético." },
 
];
