const productos = [
  { nombre: "43 BCAA + GLUTAMINA", categoria: "AMINOACIDOS/GLUTAMINAS", marca: "43 SUPPLEMENTS", imagen: "BCAA_GLUTA.png", menudeo: 390, mayoreo3k: 255, mayoreo6k: 237 },
  { nombre: "43 GAINER", categoria: "GANADORES DE PESO", marca: "43 SUPPLEMENTS", imagen: "43_GAINER.png", menudeo: 850, mayoreo3k: 680, mayoreo6k: 660 },
  { nombre: "43 RODILLERAS", categoria: "ACCESORIOS", marca: "43 SUPPLEMENTS", imagen: "43_RODILLERAS.png", menudeo: 350, mayoreo3k: 240, mayoreo6k: 225 },
  { nombre: "43 WHEY COSTAL", categoria: "PROTEINAS", marca: "43 SUPPLEMENTS", imagen: "43_WHEY.png", menudeo: 585, mayoreo3k: 425, mayoreo6k: 407 },
  { nombre: "43 ZERO 10 KG", categoria: "PROTEINAS", marca: "43 SUPPLEMENTS", imagen: "43_ZERO_10_KG.png", menudeo: 1390, mayoreo3k: 1120, mayoreo6k: 1097 },
  { nombre: "43 ZERO 2.4 KG", categoria: "PROTEINAS", marca: "43 SUPPLEMENTS", imagen: "43_ZERO_24_KG.png", menudeo: 600, mayoreo3k: 475, mayoreo6k: 460 },
  { nombre: "43 ZERO 5 KG MULTISABOR", categoria: "PROTEINAS", marca: "43 SUPPLEMENTS", imagen: "43_ZERO_MULTISABOR.png", menudeo: 900, mayoreo3k: 730, mayoreo6k: 710 },
  { nombre: "43 ZERO 6 KG", categoria: "PROTEINAS", marca: "43 SUPPLEMENTS", imagen: "43_ZERO_6KG.png", menudeo: 990, mayoreo3k: 785, mayoreo6k: 762 },
  { nombre: "ACXION", categoria: "FARMACOLOGIA", marca: "IFA", imagen: "AXCION.png", menudeo: 490, mayoreo3k: 340, mayoreo6k: 325 },
  { nombre: "AMINO ENERGY ON CHICO", categoria: "AMINOACIDOS", marca: "ON", imagen: "AMINO_ENERGY_ON_CHICO.png", menudeo: 480, mayoreo3k: 335, mayoreo6k: 320 },
  { nombre: "AMINO ENERGY ON GRANDE", categoria: "AMINOACIDOS", marca: "ON", imagen: "AMINO_ENERGY_ON_GRANDE.png", menudeo: 820, mayoreo3k: 643, mayoreo6k: 620 },
  { nombre: "AMINO X CHICO", categoria: "AMINOACIDOS", marca: "BSN", imagen: "AMINO_X_CHICO.png", menudeo: 480, mayoreo3k: 331, mayoreo6k: 316 },
  { nombre: "AMINO X GRANDE", categoria: "AMINOACIDOS", marca: "BSN", imagen: "AMINO_X_GRANDE.png", menudeo: 850, mayoreo3k: 677, mayoreo6k: 657 },
  { nombre: "AMINOJECT", categoria: "AMINOACIDOS", marca: "EVOGEN", imagen: "AMINOJECT.png", menudeo: 630, mayoreo3k: 520, mayoreo6k: 505 },
  { nombre: "ANGUS MASS", categoria: "GANADORES DE PESO", marca: "BHP", imagen: "ANGUS_MASS.png", menudeo: 740, mayoreo3k: 629, mayoreo6k: 614 },
  { nombre: "ANIMAL FLEX", categoria: "COLAGENOS", marca: "UNIVERSAL", imagen: "ANIMAL_FLEX.png", menudeo: 600, mayoreo3k: 508, mayoreo6k: 496 },
  { nombre: "ANIMAL PACK", categoria: "VITAMINAS", marca: "UNIVERSAL", imagen: "ANIMAL_PAK.png", menudeo: 770, mayoreo3k: 690, mayoreo6k: 678 },
  { nombre: "B NOVA BCAA", categoria: "AMINOACIDOS", marca: "B NOVA", imagen: "BCAA_BNOVA.png", menudeo: 350, mayoreo3k: 205, mayoreo6k: 190 },
  { nombre: "B NOVA CREATINA CHICA", categoria: "CREATINAS", marca: "B NOVA", imagen: "B_NOVA_CREATINA_CHICA.png", menudeo: 330, mayoreo3k: 235, mayoreo6k: 223 },
  { nombre: "B NOVA CREATINA GRANDE", categoria: "CREATINAS", marca: "B NOVA", imagen: "B_NOVA_CREATINA_GRANDE.png", menudeo: 400, mayoreo3k: 290, mayoreo6k: 275 },
  { nombre: "B NOVA ISO FEMME 1 KG", categoria: "PROTEINAS", marca: "B NOVA", imagen: "B_NOVA_ISO_FEMME.png", menudeo: 350, mayoreo3k: 260, mayoreo6k: 248 },
  { nombre: "B NOVA PEPTONAS", categoria: "OTROS", marca: "B NOVA", imagen: "B_NOVA_PEPTONAS.png", menudeo: 480, mayoreo3k: 290, mayoreo6k: 270 },
  { nombre: "B NOVA ZERO 1 KG", categoria: "PROTEINAS", marca: "B NOVA", imagen: "B_NOVA_ZERO_1KG.png", menudeo: 330, mayoreo3k: 245, mayoreo6k: 233 },
  { nombre: "B NOVA ZERO 4.5 KG", categoria: "PROTEINAS", marca: "B NOVA", imagen: "B_NOVA_ZERO_4.5KG.png", menudeo: 670, mayoreo3k: 555, mayoreo6k: 540 },
  { nombre: "BCAA MUTANT", categoria: "AMINOACIDOS", marca: "MUTANT", imagen: "BCAA_MUTAN.png", menudeo: 400, mayoreo3k: 274, mayoreo6k: 259 },
  { nombre: "BCAA SUPREME", categoria: "AMINOACIDOS", marca: "USP LABS", imagen: "BCAA_SUPREME.png", menudeo: 470, mayoreo3k: 348, mayoreo6k: 333 },
  { nombre: "BETA ALANINA GAT", categoria: "PRE ENTRENOS", marca: "GAT SPORT", imagen: "BETA-ALANINA.png", menudeo: 490, mayoreo3k: 372, mayoreo6k: 357 },
  { nombre: "BHP WHEY ULTRA", categoria: "PROTEINAS", marca: "BHP", imagen: "WHEY_ULTRA_BHP.png", menudeo: 840, mayoreo3k: 755, mayoreo6k: 743 },
  { nombre: "BLACK SPIDER", categoria: "QUEMADORES", marca: "CLOMA PHARMA", imagen: "BLACK_SPIDER.png", menudeo: 500, mayoreo3k: 333, mayoreo6k: 315 },
  { nombre: "BLIFE 3 MAG BLEND", categoria: "OTROS", marca: "BLIFE", imagen: "BLIFE_3_MAG_BLEND.png", menudeo: 290, mayoreo3k: 189, mayoreo6k: 177 },
  { nombre: "BLIFE 80 BILLION PROBIOTIC", categoria: "OTROS", marca: "BLIFE", imagen: "BLIFE_80_BILLION_PROBIOTICS.png", menudeo: 400, mayoreo3k: 312, mayoreo6k: 300 },
  { nombre: "BLIFE ACIDO ALFA LIPOICO", categoria: "OTROS", marca: "BLIFE", imagen: "BLIFE_ACIDO_ALFA_LIPOICO.png", menudeo: 480, mayoreo3k: 380, mayoreo6k: 368 },
  { nombre: "BLIFE ASHWAGANDA", categoria: "OTROS", marca: "BLIFE", imagen: "BLIFE_ASHWAGANDA.png", menudeo: 390, mayoreo3k: 288, mayoreo6k: 273 },
  { nombre: "BLIFE B YEAST BLEND", categoria: "VITAMINAS", marca: "BLIFE", imagen: "BLIFE_BYEAST_BLEND.png", menudeo: 290, mayoreo3k: 189, mayoreo6k: 177 },
  { nombre: "BLIFE BOTELLA CON FUNDA", categoria: "ACCESORIOS", marca: "BLIFE", imagen: "BLIFE_BOTELLA_CON_FUNDA.png", menudeo: 390, mayoreo3k: 313, mayoreo6k: 301 },
  { nombre: "BLIFE BOTELLA CON TOALLA", categoria: "ACCESORIOS", marca: "BLIFE", imagen: "BLIFE_BOTELLA_CON_TOALLA.png", menudeo: 260, mayoreo3k: 176, mayoreo6k: 164 },
  { nombre: "BLIFE BOTELLA TÉRMICA", categoria: "ACCESORIOS", marca: "BLIFE", imagen: "BLIFE_BOTELLA_TERMICA.png", menudeo: 320, mayoreo3k: 243, mayoreo6k: 231 },
  { nombre: "BLIFE CALCIO+D3", categoria: "VITAMINAS", marca: "BLIFE", imagen: "BLIFE_CALCIO_D3.png", menudeo: 370, mayoreo3k: 294, mayoreo6k: 282 },
  { nombre: "BLIFE CALOSTRO BOVINO", categoria: "OTROS", marca: "BLIFE", imagen: "BLIFE_CALOSTRO.png", menudeo: 490, mayoreo3k: 414, mayoreo6k: 402 },
  { nombre: "BLIFE CITRATO DE MAGNESIO CHICO", categoria: "OTROS", marca: "BLIFE", imagen: "BLIFE_CITRATO_DE_MAGNESIO.png", menudeo: 320, mayoreo3k: 215, mayoreo6k: 200 },
  { nombre: "BLIFE CITRATO DE MAGNESIO GRANDE", categoria: "OTROS", marca: "BLIFE", imagen: "BLIFE_CITRATO_DE_MAGNESIO.png", menudeo: 440, mayoreo3k: 322, mayoreo6k: 307 },
  { nombre: "BLIFE CITRATO DE POTASIO", categoria: "OTROS", marca: "BLIFE", imagen: "BLIFE_CITRATO_DE_POTASIO.png", menudeo: 280, mayoreo3k: 197, mayoreo6k: 185 },
  { nombre: "BLIFE COLAGENO BIO", categoria: "COLAGENOS", marca: "BLIFE", imagen: "BLIFE_COLAGENO_BIO.png", menudeo: 290, mayoreo3k: 197, mayoreo6k: 185 },
  { nombre: "BLIFE COLAGENO BLEND", categoria: "COLAGENOS", marca: "BLIFE", imagen: "BLIFE_COLAGENO_BLEND.png", menudeo: 290, mayoreo3k: 220, mayoreo6k: 208 },
  { nombre: "BLIFE CREATINA", categoria: "CREATINAS", marca: "BLIFE", imagen: "CREATINA_BLIFE.png", menudeo: 490, mayoreo3k: 389, mayoreo6k: 377 },
  { nombre: "BLIFE D3 PLUS", categoria: "VITAMINAS", marca: "BLIFE", imagen: "BLIFE_D3_PLUS.png", menudeo: 400, mayoreo3k: 312, mayoreo6k: 300 },
  { nombre: "BLIFE ELECTRO BLEND + CREATINA", categoria: "CREATINAS", marca: "BLIFE", imagen: "BLIFE_ELECTRO_BLEND_CREATINA.png", menudeo: 470, mayoreo3k: 380, mayoreo6k: 368 },
  { nombre: "BLIFE GLICINATO DE MAGNESIO", categoria: "OTROS", marca: "BLIFE", imagen: "BLIFE_GLICINATO_DE_MAGNESIO.png", menudeo: 300, mayoreo3k: 210, mayoreo6k: 198 },
  { nombre: "BLIFE JOINT BLEND", categoria: "COLAGENOS", marca: "BLIFE", imagen: "BLIFE_JOINT_BLEND.png", menudeo: 340, mayoreo3k: 244, mayoreo6k: 232 },
  { nombre: "BLIFE KIT TOALLAS", categoria: "ACCESORIOS", marca: "BLIFE", imagen: "KIT_DE_5_TOALLAS_BLIFE.png", menudeo: 280, mayoreo3k: 189, mayoreo6k: 177 },
  { nombre: "BLIFE MACA BLEND", categoria: "OTROS", marca: "BLIFE", imagen: "BLIFE_MACA_BLEND.png", menudeo: 270, mayoreo3k: 189, mayoreo6k: 177 },
  { nombre: "BLIFE MENS BLEND", categoria: "VITAMINAS", marca: "BLIFE", imagen: "BLIFE_MENS_BLEND.png", menudeo: 290, mayoreo3k: 189, mayoreo6k: 177 },
  { nombre: "BLIFE MENS T PLATINUM", categoria: "PRECURSORES", marca: "BLIFE", imagen: "BLIFE_MENS_T_PLATINUM.png", menudeo: 490, mayoreo3k: 380, mayoreo6k: 368 },
  { nombre: "BLIFE MYO INOSITOL", categoria: "OTROS", marca: "BLIFE", imagen: "BLIFE_INOSITOL.png", menudeo: 290, mayoreo3k: 196, mayoreo6k: 184 },
  { nombre: "BLIFE OMEGA 3 CHICO", categoria: "VITAMINAS", marca: "BLIFE", imagen: "BLIFE_OMEGA_3_CHICO.png", menudeo: 330, mayoreo3k: 220, mayoreo6k: 205 },
  { nombre: "BLIFE OMEGA 3 GRANDE", categoria: "VITAMINAS", marca: "BLIFE", imagen: "BLIFE_OMEGA_3_GRANDE.png", menudeo: 480, mayoreo3k: 356, mayoreo6k: 341 },
  { nombre: "BLIFE RESVERATROL", categoria: "OTROS", marca: "BLIFE", imagen: "BLIFE_RESVERATROL.png", menudeo: 320, mayoreo3k: 235, mayoreo6k: 223 },
  { nombre: "BLIFE TRIBULUS", categoria: "PRECURSORES", marca: "BLIFE", imagen: "BLIFE_TRIBULUS.png", menudeo: 350, mayoreo3k: 278, mayoreo6k: 266 },
  { nombre: "BLIFE VITAMINA E+BIOTINA", categoria: "VITAMINAS", marca: "BLIFE", imagen: "BLIFE_VITAMINA_E_BIOTINA.png", menudeo: 360, mayoreo3k: 278, mayoreo6k: 266 },
  { nombre: "BLIFE WOMENS BLEND", categoria: "VITAMINAS", marca: "BLIFE", imagen: "BLIFE_WOMENS_BLEND.png", menudeo: 300, mayoreo3k: 199, mayoreo6k: 184 },
  { nombre: "C4 ORIGINAL CHICO", categoria: "PRE ENTRENOS", marca: "CELLUCOR", imagen: "C4_ORIGINAL_CHICO.png", menudeo: 470, mayoreo3k: 353, mayoreo6k: 338 },
  { nombre: "C4 ORIGINAL GRANDE", categoria: "PRE ENTRENOS", marca: "CELLUCOR", imagen: "C4_ORIGINAL_GRANDE.png", menudeo: 640, mayoreo3k: 505, mayoreo6k: 490 },
  { nombre: "CAFEINA GAT", categoria: "PRE ENTRENOS", marca: "GAT SPORT", imagen: "CAFEINA_GAT.png", menudeo: 280, mayoreo3k: 170, mayoreo6k: 158 },
  { nombre: "CAFEINA MUTANT", categoria: "PRE ENTRENOS", marca: "MUTANT", imagen: "CAFEINA_MUTANT.png", menudeo: 300, mayoreo3k: 195, mayoreo6k: 180 },
  { nombre: "CARBOTEIN", categoria: "AMINOACIDOS", marca: "GAT SPORT", imagen: "CARBOTEIN.png", menudeo: 640, mayoreo3k: 529, mayoreo6k: 514 },
  { nombre: "CARNIVOR BOTE", categoria: "PROTEINAS", marca: "MUSCLEMEDS", imagen: "CARNIVOR", menudeo: 980, mayoreo3k: 871, mayoreo6k: 856 },
  { nombre: "CARNIVOR MASS", categoria: "GANADORES DE PESO", marca: "MUSCLEMEDS", imagen: "CARNIVOR_MASS.png", menudeo: 870, mayoreo3k: 749, mayoreo6k: 734 },
  { nombre: "CBUM ESSENTIAL CHICO", categoria: "PRE ENTRENOS", marca: "RAW", imagen: "CBUM_ESSENTIAL_CHICO.png", menudeo: 490, mayoreo3k: 375, mayoreo6k: 360 },
  { nombre: "CBUM ITHOLATE CHICA", categoria: "PROTEINAS", marca: "RAW", imagen: "CBUM_ITHOLATE_CHICA.png", menudeo: 840, mayoreo3k: 749, mayoreo6k: 737 },
  { nombre: "CBUM ITHOLATE GRANDE", categoria: "PROTEINAS", marca: "RAW", imagen: "CBUM_ITHOLATE_GRANDE.png", menudeo: 1640, mayoreo3k: 1509, mayoreo6k: 1494 },
  { nombre: "CELL TECH 3 LBS", categoria: "CREATINAS", marca: "MUSCLETECH", imagen: "CELL_TECH_3LBS", menudeo: 590, mayoreo3k: 478, mayoreo6k: 463 },
  { nombre: "CELL TECH 6LBS", categoria: "CREATINAS", marca: "MUSCLETECH", imagen: "CELL_TECH_6LBS.png", menudeo: 850, mayoreo3k: 699, mayoreo6k: 681 },
  { nombre: "CELL TECH CREACTOR", categoria: "CREATINAS", marca: "MUSCLETECH", imagen: "CELL-TECH_CREACTOR.png", menudeo: 500, mayoreo3k: 374, mayoreo6k: 359 },
  { nombre: "CINTURON", categoria: "ACCESORIOS", marca: "-", imagen: "CINTURON.png", menudeo: 500, mayoreo3k: 390, mayoreo6k: 375 },
  { nombre: "CITRULINA ADVANCED", categoria: "PRE ENTRENOS", marca: "ADVANCED NUTRITION", imagen: "CITRULINA_ADVANCED.png", menudeo: 450, mayoreo3k: 349, mayoreo6k: 334 },
  { nombre: "CITRULINA INSANE", categoria: "PRE ENTRENOS", marca: "INSANE", imagen: "CITRULINA_INSANE.png", menudeo: 320, mayoreo3k: 218, mayoreo6k: 203 },
  { nombre: "CLA 1250 GAT", categoria: "QUEMADORES", marca: "GAT SPORT", imagen: "CLA_1250.png", menudeo: 350, mayoreo3k: 242, mayoreo6k: 230 },
  { nombre: "CLA+CARNITINA BPI", categoria: "QUEMADORES", marca: "BPI", imagen: "CLA_CARNITINA.png", menudeo: 450, mayoreo3k: 313, mayoreo6k: 295 },
  { nombre: "COFFEE MAX", categoria: "PRE ENTRENOS", marca: "BHP", imagen: "COFFEE_MAX.png", menudeo: 430, mayoreo3k: 338, mayoreo6k: 326 },
  { nombre: "COLÁGENO HIDROLIZADO SHE FIT", categoria: "COLAGENOS", marca: "BHP", imagen: "COLAGENO_HIDROLIZADO.png", menudeo: 440, mayoreo3k: 335, mayoreo6k: 320 },
  { nombre: "COLÁGENO META", categoria: "COLAGENOS", marca: "META", imagen: "COLAGENO_META.png", menudeo: 440, mayoreo3k: 316, mayoreo6k: 301 },
  { nombre: "CREATINA BIRDMAN", categoria: "CREATINAS", marca: "BIRDMAN", imagen: "CREATINA_BIRDMAN.png", menudeo: 590, mayoreo3k: 443, mayoreo6k: 428 },
  { nombre: "CREATINA CELLUCOR", categoria: "CREATINAS", marca: "CELLUCOR", imagen: "CREATINA_CELLUCOR.png", menudeo: 560, mayoreo3k: 410, mayoreo6k: 390 },
  { nombre: "CREATINA CREAKON CX8", categoria: "CREATINAS", marca: "MUTANT", imagen: "CREAKONG_CX8.png", menudeo: 400, mayoreo3k: 283, mayoreo6k: 268 },
  { nombre: "CREATINA DRAGON CHICA", categoria: "CREATINAS", marca: "DRAGON PHARMA", imagen: "CREATINA_DRAGON_CHICA.png", menudeo: 460, mayoreo3k: 348, mayoreo6k: 333 },
  { nombre: "CREATINA DRAGON GRANDE", categoria: "CREATINAS", marca: "DRAGON PHARMA", imagen: "CREATINA_DRAGON_GRANDE.png", menudeo: 720, mayoreo3k: 580, mayoreo6k: 565 },
  { nombre: "CREATINA ELECTROLYTE", categoria: "CREATINAS", marca: "BIRDMAN", imagen: "CREATINA_ELECTROLYTE.png", menudeo: 500, mayoreo3k: 390, mayoreo6k: 375 },
  { nombre: "CREATINA GAT CHICA", categoria: "CREATINAS", marca: "GAT SPORT", imagen: "CREATINA_GAT_CHICA.png", menudeo: 620, mayoreo3k: 400, mayoreo6k: 377 },
  { nombre: "CREATINA GAT GRANDE", categoria: "CREATINAS", marca: "GAT SPORT", imagen: "CREATINA_GAT_GRANDE.png", menudeo: 990, mayoreo3k: 632, mayoreo6k: 609 },
  { nombre: "CREATINA HI TECH CHICA", categoria: "CREATINAS", marca: "HTP", imagen: "CREATINA_HI_TECH_CHICA.png", menudeo: 560, mayoreo3k: 401, mayoreo6k: 381 },
  { nombre: "CREATINA HI TECH GRANDE", categoria: "CREATINAS", marca: "HTP", imagen: "CREATINA_HI_TECH_GRANDE.png", menudeo: 950, mayoreo3k: 784, mayoreo6k: 766 },
  { nombre: "CREATINA INSANE", categoria: "CREATINAS", marca: "INSANE", imagen: "CREATINA_INSANE.png", menudeo: 460, mayoreo3k: 333, mayoreo6k: 318 },
  { nombre: "CREATINA META", categoria: "CREATINAS", marca: "META", imagen: "CREATINA_META.png", menudeo: 500, mayoreo3k: 355, mayoreo6k: 337 },
  { nombre: "CREATINA NUTREX CHICA", categoria: "CREATINAS", marca: "NUTREX", imagen: "CREATINA_NUTREX_CHICA.png", menudeo: 500, mayoreo3k: 335, mayoreo6k: 315 },
  { nombre: "CREATINA NUTREX GRANDE", categoria: "CREATINAS", marca: "NUTREX", imagen: "CREATINA_NUTREX_GRANDE.png", menudeo: 740, mayoreo3k: 531, mayoreo6k: 508 },
  { nombre: "CREATINA ON", categoria: "CREATINAS", marca: "ON", imagen: "CREATINA_ON.png", menudeo: 590, mayoreo3k: 393, mayoreo6k: 370 },
  { nombre: "CREATINA PLATINUM", categoria: "CREATINAS", marca: "MUSCLETECH", imagen: "CREATINA_PLATINUM.png", menudeo: 650, mayoreo3k: 485, mayoreo6k: 467 },
  { nombre: "CREATINA RC CHICA", categoria: "CREATINAS", marca: "RONNIE COLEMAN", imagen: "CREATINA_RC_CHICA.png", menudeo: 460, mayoreo3k: 297, mayoreo6k: 279 },
  { nombre: "CREATINA RC GRANDE", categoria: "CREATINAS", marca: "RONNIE COLEMAN", imagen: "CREATINA_RC_GRANDE.png", menudeo: 890, mayoreo3k: 585, mayoreo6k: 562 },
  { nombre: "CREATINA ULTRA BHP 300 GRS", categoria: "CREATINAS", marca: "BHP", imagen: "CREATINA_ULTRA_BHP_300GRS.png", menudeo: 370, mayoreo3k: 214, mayoreo6k: 196 },
  { nombre: "CREATINA ULTRA BHP 500 GRS", categoria: "CREATINAS", marca: "BHP", imagen: "CREATINA_ULTRA_BHP_500GRS.png", menudeo: 420, mayoreo3k: 249, mayoreo6k: 231 },
  { nombre: "DEFIT CREATINA CHICA", categoria: "CREATINAS", marca: "DEFIT", imagen: "DEFIT_CREATINA_CHICA.png", menudeo: 340, mayoreo3k: 220, mayoreo6k: 205 },
  { nombre: "DEFIT CREATINA GRANDE", categoria: "CREATINAS", marca: "DEFIT", imagen: "DEFIT_CREATINA_GRANDE.png", menudeo: 430, mayoreo3k: 295, mayoreo6k: 280 },
  { nombre: "DEFIT FIT FEMME", categoria: "PROTEINAS", marca: "DEFIT", imagen: "DEFIT_FIT_FEMME.png", menudeo: 350, mayoreo3k: 205, mayoreo6k: 190 },
  { nombre: "DEFIT ISOLATE WHEY CHICA", categoria: "PROTEINAS", marca: "DEFIT", imagen: "DEFIT_ISOLATE_WHEY_CHICA.png", menudeo: 330, mayoreo3k: 205, mayoreo6k: 190 },
  { nombre: "DEFIT ISOLATE WHEY GRANDE", categoria: "PROTEINAS", marca: "DEFIT", imagen: "DEFIT_ISOLATE_WHEY_GRANDE.png", menudeo: 620, mayoreo3k: 445, mayoreo6k: 425 },
  { nombre: "DEFIT PEPTONAS", categoria: "OTROS", marca: "DEFIT", imagen: "DEFIT_PEPTONAS.png", menudeo: 450, mayoreo3k: 285, mayoreo6k: 265 },
  { nombre: "DEMON BCAA", categoria: "AMINOACIDOS", marca: "INSANE", imagen: "DEMON_BCAA.png", menudeo: 490, mayoreo3k: 348, mayoreo6k: 330 },
  { nombre: "DEMON DUST", categoria: "PRE ENTRENOS", marca: "INSANE", imagen: "DEMON_DUST.png", menudeo: 430, mayoreo3k: 289, mayoreo6k: 274 },
  { nombre: "ELITE WHEY 5 LBS", categoria: "PROTEINAS", marca: "DYMATIZE", imagen: "ELITE_100_WHEY.png", menudeo: 1270, mayoreo3k: 1157, mayoreo6k: 1142 },
  { nombre: "EVP 3D", categoria: "PRE ENTRENOS", marca: "EVOGEN", imagen: "EVP_3D.png", menudeo: 680, mayoreo3k: 550, mayoreo6k: 535 },
  { nombre: "EVP XTREME", categoria: "PRE ENTRENOS", marca: "EVOGEN", imagen: "EVP_XTREME.png", menudeo: 680, mayoreo3k: 606, mayoreo6k: 594 },
  { nombre: "FALCON PERFORMANCE", categoria: "PROTEINAS", marca: "BIRDMAN", imagen: "FALCON_PERFORMANCE.png", menudeo: 730, mayoreo3k: 601, mayoreo6k: 586 },
  { nombre: "FARMACOLOGIA ROTTERDAM", categoria: "FARMACOLOGIA", marca: "ROTTERDAM", imagen: "FARMACOLOGIA_ROTTERDAM.png", menudeo: 600, mayoreo3k: 450, mayoreo6k: 435 },
  { nombre: "FARMACOLOGIA SYNTEX LABS", categoria: "FARMACOLOGIA", marca: "SYNTEX LABS", imagen: "FARMACOLOGIA_SYNTEX_LABS.png", menudeo: 600, mayoreo3k: 420, mayoreo6k: 402 },
  { nombre: "FARMACOLOGIA XT LABS", categoria: "FARMACOLOGIA", marca: "XT LABS", imagen: "FARMACOLOGIA_XT_LABS.png", menudeo: 600, mayoreo3k: 450, mayoreo6k: 435 },
  { nombre: "FITMINGO", categoria: "PROTEINAS", marca: "BIRDMAN", imagen: "FITMINGO.png", menudeo: 960, mayoreo3k: 823, mayoreo6k: 805 },
  { nombre: "FLEXX EAAS", categoria: "AMINOACIDOS", marca: "GAT SPORT", imagen: "FLEXX_EAAS.png", menudeo: 450, mayoreo3k: 375, mayoreo6k: 363 },
  { nombre: "GAINER ULTRA", categoria: "GANADORES DE PESO", marca: "BHP", imagen: "GAINER_ULTRA.png", menudeo: 720, mayoreo3k: 639, mayoreo6k: 627 },
  { nombre: "GHOST LEGEND PWO", categoria: "PRE ENTRENOS", marca: "GHOST", imagen: "GHOST_LEGEND.png", menudeo: 660, mayoreo3k: 580, mayoreo6k: 568 },
  { nombre: "GHOST WHEY 2 LBS", categoria: "PROTEINAS", marca: "GHOST", imagen: "GHOST_WHEY.png", menudeo: 800, mayoreo3k: 692, mayoreo6k: 677 },
  { nombre: "GLUTAMINA PURE CHICA", categoria: "GLUTAMINAS", marca: "NUTREX", imagen: "GLUTAMINA_PURE_CHICA.png", menudeo: 320, mayoreo3k: 246, mayoreo6k: 234 },
  { nombre: "GLUTAMINA PURE GRANDE", categoria: "GLUTAMINAS", marca: "NUTREX", imagen: "GLUTAMINA_PURE_GRANDE.png", menudeo: 600, mayoreo3k: 518, mayoreo6k: 506 },
  { nombre: "GLUTAMINA GAT", categoria: "GLUTAMINAS", marca: "GAT SPORT", imagen: "GLUTAMINA_GAT.png", menudeo: 390, mayoreo3k: 276, mayoreo6k: 261 },
  { nombre: "GLUTAMINA MUTANT", categoria: "GLUTAMINAS", marca: "MUTANT", imagen: "GLUTAMINA_MUTANT.png", menudeo: 330, mayoreo3k: 223, mayoreo6k: 211 },
  { nombre: "GLUTAMINA PLATINUM", categoria: "GLUTAMINAS", marca: "MUSCLETECH", imagen: "GLUTAMINA_PLATINUM.png", menudeo: 420, mayoreo3k: 339, mayoreo6k: 327 },
  { nombre: "GOLD STANDARD 10 LBS", categoria: "PROTEINAS", marca: "ON", imagen: "GOLD_ESTANDAR_10_LBS.png", menudeo: 2320, mayoreo3k: 2168, mayoreo6k: 2150 },
  { nombre: "GOLD STANDARD 2 LBS", categoria: "PROTEINAS", marca: "ON", imagen: "GOLD_STANDARD_WHEY.png", menudeo: 790, mayoreo3k: 665, mayoreo6k: 650 },
  { nombre: "GOLD STANDARD 5 LBS", categoria: "PROTEINAS", marca: "ON", imagen: "GOLD_STANDARD_WHEY.png", menudeo: 1420, mayoreo3k: 1279, mayoreo6k: 1264 },
  { nombre: "GOLD STANDARD ISOLATE", categoria: "PROTEINAS", marca: "ON", imagen: "GOLD_STANDARD_ISOLATE.png", menudeo: 1570, mayoreo3k: 1467, mayoreo6k: 1455 },
  { nombre: "HYDROTEIN", categoria: "PROTEINAS", marca: "ADVANCED NUTRITION", imagen: "HYDROTEIN.png", menudeo: 970, mayoreo3k: 870, mayoreo6k: 858 },
  { nombre: "HYDROXYCUT HARDCORE ELITE", categoria: "QUEMADORES", marca: "MUSCLETECH", imagen: "HYDROXYCUT.png", menudeo: 450, mayoreo3k: 335, mayoreo6k: 320 },
  { nombre: "INSANE VEINZ", categoria: "PRE ENTRENOS", marca: "INSANE", imagen: "INSANE_VEINZ.png", menudeo: 470, mayoreo3k: 364, mayoreo6k: 352 },
  { nombre: "ISOPHORM", categoria: "PROTEINAS", marca: "DRAGON PHARMA", imagen: "ISOPHORM.png", menudeo: 1650, mayoreo3k: 1563, mayoreo6k: 1551 },
  { nombre: "ISO 100 1.3 LBS", categoria: "PROTEINAS", marca: "DYMATIZE", imagen: "ISO_100.png", menudeo: 820, mayoreo3k: 674, mayoreo6k: 659 },
  { nombre: "ISO 100 3 LBS", categoria: "PROTEINAS", marca: "DYMATIZE", imagen: "ISO_100_3_LBS.png", menudeo: 1280, mayoreo3k: 1165, mayoreo6k: 1150 },
  { nombre: "ISO 100 5 LBS", categoria: "PROTEINAS", marca: "DYMATIZE", imagen: "ISO_100_5_LBS.png", menudeo: 1850, mayoreo3k: 1743, mayoreo6k: 1728 },
  { nombre: "ISOFIT", categoria: "PROTEINAS", marca: "NUTREX", imagen: "ISOFIT_5_LBS.png", menudeo: 1350, mayoreo3k: 1217, mayoreo6k: 1202 },
  { nombre: "ISOPURE", categoria: "PROTEINAS", marca: "NATURE BEST", imagen: "ISOPURE_ZERO_CARB.png", menudeo: 1240, mayoreo3k: 1130, mayoreo6k: 1115 },
  { nombre: "ISOPURE GRANDE", categoria: "PROTEINAS", marca: "NATURE BEST", imagen: "ISOPURE_GRANDE.png", menudeo: 1650, mayoreo3k: 1494, mayoreo6k: 1474 },
  { nombre: "JOINT SUPPORT GAT", categoria: "COLAGENOS", marca: "GAT SPORT", imagen: "JOINT_SUPPORT.png", menudeo: 380, mayoreo3k: 296, mayoreo6k: 284 },
  { nombre: "L ARGININA GAT", categoria: "PRE ENTRENOS", marca: "GAT SPORT", imagen: "L-ARGININA.png", menudeo: 400, mayoreo3k: 314, mayoreo6k: 302 },
  { nombre: "L CARNITINA GAT CAPS", categoria: "QUEMADORES", marca: "GAT SPORT", imagen: "L-CARNITINA.png", menudeo: 340, mayoreo3k: 227, mayoreo6k: 212 },
  { nombre: "L CARNITINA ULTRA LIQUIDA", categoria: "QUEMADORES", marca: "BHP", imagen: "L-CARNITINA.png", menudeo: 290, mayoreo3k: 185, mayoreo6k: 173 },
  { nombre: "LIPO 6 BLACK HERS 60 CAPS", categoria: "QUEMADORES", marca: "NUTREX", imagen: "LIPO_6_BLACK_HERS_60_CAPS.png", menudeo: 440, mayoreo3k: 301, mayoreo6k: 286 },
  { nombre: "LIPO 6 BLACK ROJO 120 CAPS", categoria: "QUEMADORES", marca: "NUTREX", imagen: "LIPO_6_BLACK.png", menudeo: 440, mayoreo3k: 308, mayoreo6k: 293 },
  { nombre: "LIPODRENE AMARILLO", categoria: "QUEMADORES", marca: "HTP", imagen: "LIPODRENE_AMARILLO.png", menudeo: 600, mayoreo3k: 458, mayoreo6k: 443 },
  { nombre: "LIPODRENE NEGRO", categoria: "QUEMADORES", marca: "HTP", imagen: "LIPODRENE_NEGRO.png", menudeo: 600, mayoreo3k: 459, mayoreo6k: 444 },
  { nombre: "LIPODRENE VERDE", categoria: "QUEMADORES", marca: "HTP", imagen: "LIPODRENE_VERDE.png", menudeo: 600, mayoreo3k: 456, mayoreo6k: 441 },
  { nombre: "MADNESS MUTANT", categoria: "PRE ENTRENOS", marca: "MUTANT", imagen: "MADNESS.png", menudeo: 370, mayoreo3k: 268, mayoreo6k: 253 },
  { nombre: "MAGNESIO BHP CAPS", categoria: "OTROS", marca: "BHP", imagen: "MAGNESIO.png", menudeo: 220, mayoreo3k: 130, mayoreo6k: 118 },
  { nombre: "MASS TECH EXTREME 2000", categoria: "GANADORES DE PESO", marca: "MUSCLETECH", imagen: "MASS_TECH_EXTREME.png", menudeo: 820, mayoreo3k: 693, mayoreo6k: 678 },
  { nombre: "MESOFRANCE PEPTONAS", categoria: "OTROS", marca: "MESOFRANCE", imagen: "MESOFRANCE_PEPTONAS.png", menudeo: 600, mayoreo3k: 410, mayoreo6k: 387 },
  { nombre: "MULTI VITAMIN + TEST CHICO", categoria: "VITAMINAS/PRECURSORES", marca: "GAT SPORT", imagen: "MULTI_VITAMIN_+_TEST_CHICO.png", menudeo: 350, mayoreo3k: 225, mayoreo6k: 210 },
  { nombre: "MULTI VITAMIN + TEST GRANDE", categoria: "VITAMINAS/PRECURSORES", marca: "GAT SPORT", imagen: "MULTI_VITAMIN_+_TEST_GRANDE.png", menudeo: 490, mayoreo3k: 401, mayoreo6k: 389 },
  { nombre: "MULTIVITAMINICO PLATINUM", categoria: "VITAMINAS", marca: "MUSCLETECH", imagen: "MULTIVITAMINICO_PLATINUM.png", menudeo: 350, mayoreo3k: 242, mayoreo6k: 227 },
  { nombre: "MUTANT MASS CHICO", categoria: "GANADORES DE PESO", marca: "MUTANT", imagen: "MUTANT_MASS_CHICO.png", menudeo: 590, mayoreo3k: 440, mayoreo6k: 425 },
  { nombre: "MUTANT MASS GRANDE", categoria: "GANADORES DE PESO", marca: "MUTANT", imagen: "MUTANT_MASS_GRANDE.png", menudeo: 1160, mayoreo3k: 1024, mayoreo6k: 1009 },
  { nombre: "MUTANT WHEY 10 LBS", categoria: "PROTEINAS", marca: "MUTANT", imagen: "MUTANT_WHEY_10_LBS.png", menudeo: 1590, mayoreo3k: 1433, mayoreo6k: 1413 },
  { nombre: "MUTANT WHEY 5 LBS", categoria: "PROTEINAS", marca: "MUTANT", imagen: "MUTANT_WHEY_5_LBS.png", menudeo: 920, mayoreo3k: 795, mayoreo6k: 780 },
  { nombre: "MUTANT WHEY DUAL", categoria: "PROTEINAS", marca: "MUTANT", imagen: "MUTANT_WHEY_DUAL.png", menudeo: 840, mayoreo3k: 736, mayoreo6k: 721 },
  { nombre: "NITRAFLEX", categoria: "PRE ENTRENOS", marca: "GAT SPORT", imagen: "NITRAFLEX.png", menudeo: 560, mayoreo3k: 414, mayoreo6k: 394 },
  { nombre: "NITRO TECH PERFORMANCE 4 LBS", categoria: "PROTEINAS", marca: "MUSCLETECH", imagen: "NITRO_TECH_PERFORMANCE.png", menudeo: 1050, mayoreo3k: 943, mayoreo6k: 928 },
  { nombre: "NITRO TECH WHEY GOLD 2 LBS", categoria: "PROTEINAS", marca: "MUSCLETECH", imagen: "NITRO_TECH_WHEY_GOLD_2LBS.png", menudeo: 690, mayoreo3k: 576, mayoreo6k: 561 },
  { nombre: "NITRO TECH WHEY GOLD 5 LBS", categoria: "PROTEINAS", marca: "MUSCLETECH", imagen: "NITRO_TECH_WHEY_GOLD.png", menudeo: 1190, mayoreo3k: 1048, mayoreo6k: 1033 },
  { nombre: "NITROTECH RIPPED 4 LBS", categoria: "PROTEINAS", marca: "MUSCLETECH", imagen: "NITRO_TECH_RIPPED.png", menudeo: 1060, mayoreo3k: 943, mayoreo6k: 928 },
  { nombre: "OMEGA 3 GAT", categoria: "VITAMINAS", marca: "GAT SPORT", imagen: "OMEGA-3.png", menudeo: 430, mayoreo3k: 328, mayoreo6k: 316 },
  { nombre: "OPTI MEN", categoria: "VITAMINAS", marca: "ON", imagen: "OPTI-MEN_ON.png", menudeo: 600, mayoreo3k: 519, mayoreo6k: 507 },
  { nombre: "OPTI WOMEN", categoria: "VITAMINAS", marca: "ON", imagen: "OPTI-WOMEN_ON.png", menudeo: 470, mayoreo3k: 380, mayoreo6k: 368 },
  { nombre: "PHANTOM XS", categoria: "QUEMADORES", marca: "NUBREED", imagen: "PHANTOM_XS.png", menudeo: 420, mayoreo3k: 317, mayoreo6k: 305 },
  { nombre: "PHARLABS ISOLATE", categoria: "PROTEINAS", marca: "PHARLABS", imagen: "", menudeo: 790, mayoreo3k: 640, mayoreo6k: 625 },
  { nombre: "PSYCHOTIC DORADO", categoria: "PRE ENTRENOS", marca: "INSANE", imagen: "PSYCHOTIC_DORADO.png", menudeo: 520, mayoreo3k: 381, mayoreo6k: 366 },
  { nombre: "PSYCHOTIC NEGRO", categoria: "PRE ENTRENOS", marca: "INSANE", imagen: "PSYCHOTIC_NEGRO.png", menudeo: 440, mayoreo3k: 319, mayoreo6k: 304 },
  { nombre: "PSYCHOTIC ROJO CHICO", categoria: "PRE ENTRENOS", marca: "INSANE", imagen: "PSYCHOTIC_ROJO_CHICO.png", menudeo: 460, mayoreo3k: 359, mayoreo6k: 344 },
  { nombre: "PSYCHOTIC ROJO GRANDE", categoria: "PRE ENTRENOS", marca: "INSANE", imagen: "PSYCHOTIC_ROJO_GRANDE.png", menudeo: 670, mayoreo3k: 523, mayoreo6k: 505 },
  { nombre: "PSYCHOTIC SAW", categoria: "PRE ENTRENOS", marca: "INSANE", imagen: "PSYCHOTIC_SAW.png", menudeo: 520, mayoreo3k: 412, mayoreo6k: 397 },
  { nombre: "PSYCHOTIC SAW GRANDE", categoria: "PRE ENTRENOS", marca: "INSANE", imagen: "", menudeo: 720, mayoreo3k: 577, mayoreo6k: 562 },
  { nombre: "PSYCHOTIC SOBRES NEGRO", categoria: "PRE ENTRENOS", marca: "INSANE", imagen: "PSYCHOTIC_SOBRES_NEGRO.png", menudeo: 550, mayoreo3k: 459, mayoreo6k: 447 },
  { nombre: "PSYCHOTIC SOBRES ROJO", categoria: "PRE ENTRENOS", marca: "INSANE", imagen: "PSYCHOTIC_SOBRES_ROJO.png", menudeo: 580, mayoreo3k: 492, mayoreo6k: 480 },
  { nombre: "PYSCHOTIC SOBRES DORADO", categoria: "PRE ENTRENOS", marca: "INSANE", imagen: "PSYCHOTIC_SOBRES_DORADO.png", menudeo: 590, mayoreo3k: 489, mayoreo6k: 477 },
  { nombre: "REYKON CREATINA GRANDE", categoria: "CREATINAS", marca: "REYKON", imagen: "REYKON_CREATINA_GRANDE.png", menudeo: 430, mayoreo3k: 267, mayoreo6k: 249 },
  { nombre: "REYKON PRIMATE BURST", categoria: "PROTEINAS", marca: "REYKON", imagen: "REYKON_PRIMATE_BURST.png", menudeo: 650, mayoreo3k: 485, mayoreo6k: 465 },
  { nombre: "REYKON ZERO 1 KG", categoria: "PROTEINAS", marca: "REYKON", imagen: "JUNGLE_RUSH_ZERO.png", menudeo: 350, mayoreo3k: 200, mayoreo6k: 185 },
  { nombre: "REYKON ZERO 10 KG", categoria: "PROTEINAS", marca: "REYKON", imagen: "JUNGLE_RUSH_10_KG.png", menudeo: 1350, mayoreo3k: 965, mayoreo6k: 942 },
  { nombre: "REYKON ZERO 6 KG", categoria: "PROTEINAS", marca: "REYKON", imagen: "JUNGLE_RUSH_6_KG.png", menudeo: 950, mayoreo3k: 585, mayoreo6k: 562 },
  { nombre: "REYKON ZERO MULTISABOR", categoria: "PROTEINAS", marca: "REYKON", imagen: "JUNGLE_RUSH_MULTISABOR.png", menudeo: 950, mayoreo3k: 705, mayoreo6k: 682 },
  { nombre: "RONNIE WHEY XS", categoria: "PROTEINAS", marca: "RONNIE COLEMAN", imagen: "RC_WHEY_XS.png", menudeo: 790, mayoreo3k: 674, mayoreo6k: 659 },
  { nombre: "RYSE LOADED PRE", categoria: "PRE ENTRENOS", marca: "RYSE", imagen: "RYSE_RELOADED.png", menudeo: 660, mayoreo3k: 520, mayoreo6k: 505 },
  { nombre: "SERIOUS MASS CHICO", categoria: "GANADORES DE PESO", marca: "ON", imagen: "SERIOUS_MASS_CHICO.png", menudeo: 790, mayoreo3k: 670, mayoreo6k: 655 },
  { nombre: "SERIOUS MASS GRANDE", categoria: "GANADORES DE PESO", marca: "ON", imagen: "SERIOUS_MASS_GRANDE.png", menudeo: 1220, mayoreo3k: 1084, mayoreo6k: 1069 },
  { nombre: "SHAKER COLOR LISO", categoria: "ACCESORIOS", marca: "BLENDER BOTTLE", imagen: "SHAKER_BLENDER.png", menudeo: 280, mayoreo3k: 208, mayoreo6k: 196 },
  { nombre: "SHAKER SYNTRAX", categoria: "ACCESORIOS", marca: "SYNTRAX", imagen: "SHAKER_SYNTRAX.png", menudeo: 230, mayoreo3k: 135, mayoreo6k: 123 },
  { nombre: "SHAKER GARRAFON", categoria: "ACCESORIOS", marca: "BSN", imagen: "SHAKER_GARRAFON_BSN.png", menudeo: 280, mayoreo3k: 180, mayoreo6k: 168 },
  { nombre: "SHAKER SUPER HEROES", categoria: "ACCESORIOS", marca: "PERFECT", imagen: "SHAKER_SUPER_HEROES.png", menudeo: 300, mayoreo3k: 206, mayoreo6k: 194 },
  { nombre: "STRAPS (CAYERAS)", categoria: "ACCESORIOS", marca: "-", imagen: "STRAPS_SUPERHEROES.png", menudeo: 250, mayoreo3k: 170, mayoreo6k: 158 },
  { nombre: "SUPER PUMP MAX", categoria: "PRE ENTRENOS", marca: "GASPARI", imagen: "SUPER_PUMP_MAX.png", menudeo: 590, mayoreo3k: 482, mayoreo6k: 467 },
  { nombre: "SYNTHA 6", categoria: "PROTEINAS", marca: "BSN", imagen: "SYNTHA-6.png", menudeo: 1060, mayoreo3k: 943, mayoreo6k: 928 },
  { nombre: "TESTROL GOLD", categoria: "PRECURSORES", marca: "GAT SPORT", imagen: "TESTROL_GOLD_ES.png", menudeo: 530, mayoreo3k: 350, mayoreo6k: 330 },
  { nombre: "TESTROL ORIGINAL", categoria: "PRECURSORES", marca: "GAT SPORT", imagen: "TESTROL_ORIGINAL.png", menudeo: 500, mayoreo3k: 335, mayoreo6k: 317 },
  { nombre: "THE CURSE", categoria: "PRE ENTRENOS", marca: "COBRA LABS", imagen: "THE_CURSE.png", menudeo: 500, mayoreo3k: 361, mayoreo6k: 343 },
  { nombre: "TOTAL WAR", categoria: "PRE ENTRENOS", marca: "REDCON1", imagen: "TOTAL_WAR.png", menudeo: 530, mayoreo3k: 397, mayoreo6k: 379 },
  { nombre: "VAPOR X", categoria: "PRE ENTRENOS", marca: "MUSCLETECH", imagen: "VAPOR_X5.png", menudeo: 460, mayoreo3k: 357, mayoreo6k: 342 },
  { nombre: "VEGAN NATURALS", categoria: "PROTEINAS", marca: "ADVANCED NUTRITION", imagen: "VEGAN_PROTEIN.png", menudeo: 850, mayoreo3k: 749, mayoreo6k: 734 },
  { nombre: "VENOM INFERNO", categoria: "PRE ENTRENOS", marca: "DRAGON PHARMA", imagen: "VENOM_INFERNO.png", menudeo: 520, mayoreo3k: 414, mayoreo6k: 402 },
  { nombre: "VITAMINA C INSANE", categoria: "VITAMINAS", marca: "INSANE", imagen: "VITAMINA_C_INSANE.png", menudeo: 340, mayoreo3k: 216, mayoreo6k: 201 },
  { nombre: "WHEY HD", categoria: "PROTEINAS", marca: "BPI", imagen: "WHEY_HD_BPI.png", menudeo: 990, mayoreo3k: 890, mayoreo6k: 878 },
  { nombre: "XTINCTION MULTISABOR", categoria: "PROTEINAS", marca: "XTINCTION", imagen: "WHEY_XTINCTION_MULTISABOR.png", menudeo: 850, mayoreo3k: 605, mayoreo6k: 582 },
  { nombre: "YOHIMBINE", categoria: "QUEMADORES", marca: "ALLMAX", imagen: "YOHIMBINE.png", menudeo: 350, mayoreo3k: 251, mayoreo6k: 239 },
  { nombre: "ZMAG GAT", categoria: "OTROS", marca: "GAT SPORT", imagen: "ZMAG_GAT.png", menudeo: 320, mayoreo3k: 216, mayoreo6k: 204 }
];
